name: Hello World Artifact Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.set-output.outputs.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Hello World script
        run: echo "Hello World" > hello.txt

      - name: Upload Hello World output
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-output
          path: hello.txt

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Hello World artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-world-output

      - name: Display downloaded content
        run: |
          echo "Downloaded artifact content:"
          cat hello.txt
