name: artifact1

on: [push]

env:
  FILE_NAME: hello-server

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build ${{ env.FILE_NAME }} for windows-latest
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    - name: Upload artifact for linux
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}
        
    - name: Upload artifact for windows
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe
  
  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Hello World artifact
        uses: actions/download-artifact@v4
        with:
          name: linux

      - name: Display downloaded content
        run: |
          echo "Downloaded artifact content:"
          chmod +x hello-server;./hello-server & sleep 3 && for i in Anakin Luke Leia Kylo Rey; do echo "$(date): $(curl -s http://localhost:11000/${i})"; done

        
